// <auto-generated />
using System;
using CozyTts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CozyTts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CozyTtsDbContext))]
    [Migration("20260511143758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CozyTts.Domain.Entities.AudioFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("audio_files", (string)null);
                });

            modelBuilder.Entity("CozyTts.Domain.Entities.VoiceGenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("QueueJobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("VoiceProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("VoiceProfileId");

                    b.ToTable("voice_generation_jobs", (string)null);
                });

            modelBuilder.Entity("CozyTts.Domain.Entities.VoiceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PiperConfigPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PiperModelPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("voice_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "cozy_female",
                            Description = "Warm American English voice for soft listening practice.",
                            DisplayName = "Cozy Female",
                            IsEnabled = true,
                            PiperConfigPath = "en_US-lessac-medium.onnx.json",
                            PiperModelPath = "en_US-lessac-medium.onnx"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "calm_male",
                            Description = "Calm American English male voice for dialogue narration.",
                            DisplayName = "Calm Male",
                            IsEnabled = true,
                            PiperConfigPath = "en_US-ryan-medium.onnx.json",
                            PiperModelPath = "en_US-ryan-medium.onnx"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "british_soft",
                            Description = "Soft British English profile. Replace model file if you prefer another Piper voice.",
                            DisplayName = "British Soft",
                            IsEnabled = true,
                            PiperConfigPath = "en_GB-alba-medium.onnx.json",
                            PiperModelPath = "en_GB-alba-medium.onnx"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "narrator",
                            Description = "Neutral narrator voice for monologues and long-form listening.",
                            DisplayName = "Narrator",
                            IsEnabled = true,
                            PiperConfigPath = "en_US-amy-medium.onnx.json",
                            PiperModelPath = "en_US-amy-medium.onnx"
                        });
                });

            modelBuilder.Entity("CozyTts.Domain.Entities.VoiceProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("voice_projects", (string)null);
                });

            modelBuilder.Entity("CozyTts.Domain.Entities.AudioFile", b =>
                {
                    b.HasOne("CozyTts.Domain.Entities.VoiceGenerationJob", "Job")
                        .WithOne("AudioFile")
                        .HasForeignKey("CozyTts.Domain.Entities.AudioFile", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CozyTts.Domain.Entities.VoiceGenerationJob", b =>
                {
                    b.HasOne("CozyTts.Domain.Entities.VoiceProject", "Project")
                        .WithMany("Jobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozyTts.Domain.Entities.VoiceProfile", "VoiceProfile")
                        .WithMany("Jobs")
                        .HasForeignKey("VoiceProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("VoiceProfile");
                });

            modelBuilder.Entity("CozyTts.Domain.Entities.VoiceGenerationJob", b =>
                {
                    b.Navigation("AudioFile");
                });

            modelBuilder.Entity("CozyTts.Domain.Entities.VoiceProfile", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CozyTts.Domain.Entities.VoiceProject", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
